name: RDP-Ubuntu

on:
  workflow_dispatch:

jobs:
  secure-rdp:
    runs-on: ubuntu-latest
    timeout-minutes: 360

    steps:
      - name: Update and Install XRDP + Desktop
        run: |
          sudo apt-get update
          sudo apt-get install -y xrdp xfce4 xfce4-goodies dbus-x11 x11-xserver-utils
          
          USERNAME="rdpuser"
          PASSWORD=$(tr -dc 'A-Za-z0-9!@#$%^&*' < /dev/urandom | head -c 16)
          sudo useradd -m -s /bin/bash $USERNAME
          echo "$USERNAME:$PASSWORD" | sudo chpasswd
          
          echo "RDP_CREDS=User: $USERNAME | Password: $PASSWORD" >> $GITHUB_ENV
          
          echo "startxfce4" | sudo tee /home/$USERNAME/.xsession
          sudo systemctl enable xrdp
          sudo systemctl restart xrdp

      - name: Install Tailscale
        run: |
          curl -fsSL https://tailscale.com/install.sh | sh
          sudo tailscale up --authkey=${{ secrets.TAILSCALE_AUTH_KEY }} --hostname=gh-ubuntu-$GITHUB_RUN_ID
          
          TS_IP=$(tailscale ip -4 | head -n 1)
          echo "TAILSCALE_IP=$TS_IP" >> $GITHUB_ENV

      - name: Verify RDP Accessibility
        run: |
          echo "Tailscale IP: $TAILSCALE_IP"
          nc -zv $TAILSCALE_IP 3389 || (echo "RDP port not reachable" && exit 1)

      - name: Maintain Connection
        run: |
          echo "=== RDP ACCESS ==="
          echo "Address: $TAILSCALE_IP"
          echo "Username: rdpuser"
          echo "Password: $(echo $RDP_CREDS)"
          echo "==================="
          
          while true; do
            echo "[$(date)] RDP Active..."
            sleep 300
          done
